### ISSUE TITLE
Patch firmware provided by xiegu

### ISSUE THREAD

**Issue by SydneyOwl** [OpenHamradioFirmware/G90Tools#5]
Hello,
Your project seems to involve reading the firmware that has been flashed from the G90 and making modifications. If we are modifying the firmware based on the one provided directly on the Xiegu website, does it require decrypting the firmware?

Sorry, I know almost nothing about the microcontroller field :(

**Comment by kbeckmann** [comment]
This project contains tools to extract the application and bootloader from the two microcontrollers inside the unit. Firmware files downloaded from the vendor are encrypted. The key can be extracted from the unit using the tools. The keys are not published for copyright reasons.

The additional modification scripts such as changing bandedges, logo, etc, operate on the actual application firmware binary. You could either use the extracted application binary, or a decrypted binary from the vendor (they should be equivalent).

What is your goal?

**Comment by SydneyOwl** [comment]
@kbeckmann
I am trying to modify the boot logo of my G90 but I have totally no idea how to find the key to decrypt firmware using debugger…I’ll try to figure it out!
Anyway, Thank you for your reply!

**Comment by kbeckmann** [comment]
Okay, good luck! I’m sorry I can’t give you the key directly but the steps to get it are all here in the repository.

**Comment by SydneyOwl** [comment]
@kbeckmann 
So sorry to bother you again, I just made my way to find the key to decrypt the firmware. However after decrypted the firmware I found the firmware's size is 0x1FCCF which is less than 0x20854 as you provided in patch_bootlogo.py:
![image](https://github.com/user-attachments/assets/2ec9496e-72c2-439d-9c9a-9f98c857ed3c)

which means the boot logo is attached directly to the tail of the decrypted firmware. After flashing it into the display unit the boot logo is not changed as expected.

The original firmware I downloaded is `G90_DispUnit_Fw_V1.80.xgf`:
![image](https://github.com/user-attachments/assets/9e6ab9a4-2b1a-477e-8e0a-38d20e33ffe0)

The md5 of the key I found is:
![image](https://github.com/user-attachments/assets/dd214fc1-58fc-4d7d-81b6-f6c381e5bb7e)
which should be correct.

Is there anything to do with the newest firmware? or if the position of boot logo is not fixed in the different version of firmware, is there any way to find the header of the logo in the firmware so we can change it directly?

Thank you so much for your reply!

**Comment by kbeckmann** [comment]
Your key is correct. I updated the tool to patch v1.80 as well as some others. I also added a tool to try to find the offset in case it is unknown. Hope it works for you!

**Comment by SydneyOwl** [comment]
@kbeckmann It works! Thank you for your help!!

**Comment by kbeckmann** [comment]
Awesome!
